In [1]:
pip install tensorflow

In [5]:
import tensorflow as tf
print("TensorFlow version:", tf.__version__)


TensorFlow version: 2.17.1


In [4]:
# Scalars
scalar = tf.constant(5)

# Vectors
vector = tf.constant([1, 2, 3])

# Matrices
matrix = tf.constant([[1, 2], [3, 4]])

# Higher-dimensional Tensors
tensor = tf.constant([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])


In [6]:
# Scalars
scalar = tf.constant(5)
print("Scalar:", scalar)

# Vectors
vector = tf.constant([1, 2, 3])
print("Vector:", vector)

# Matrices
matrix = tf.constant([[1, 2], [3, 4]])
print("Matrix:\n", matrix)

# Higher-dimensional Tensors
tensor = tf.constant([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("Tensor:\n", tensor)


Scalar: tf.Tensor(5, shape=(), dtype=int32)
Vector: tf.Tensor([1 2 3], shape=(3,), dtype=int32)
Matrix:
 tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
Tensor:
 tf.Tensor(
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]], shape=(2, 2, 2), dtype=int32)


In [7]:
print("Shape of tensor:", tensor.shape)
print("Data type of tensor:", tensor.dtype)
print("Number of dimensions (rank):", tensor.ndim)


Shape of tensor: (2, 2, 2)
Data type of tensor: <dtype: 'int32'>
Number of dimensions (rank): 3


In [8]:
a = tf.constant([1, 2, 3])
b = tf.constant([4, 5, 6])

# Add
add = tf.add(a, b)
print("Addition:", add)

# Subtract
sub = tf.subtract(a, b)
print("Subtraction:", sub)

# Multiply
mul = tf.multiply(a, b)
print("Multiplication:", mul)

# Divide
div = tf.divide(a, b)
print("Division:", div)

# Matrix Multiplication
matrix_a = tf.constant([[1, 2], [3, 4]])
matrix_b = tf.constant([[5, 6], [7, 8]])
result = tf.matmul(matrix_a, matrix_b)
print("Matrix Multiplication:\n", result)


Addition: tf.Tensor([5 7 9], shape=(3,), dtype=int32)
Subtraction: tf.Tensor([-3 -3 -3], shape=(3,), dtype=int32)
Multiplication: tf.Tensor([ 4 10 18], shape=(3,), dtype=int32)
Division: tf.Tensor([0.25 0.4  0.5 ], shape=(3,), dtype=float64)
Matrix Multiplication:
 tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)
