In [ ]:
import numpy as np
x = np.array([[1,0,1],[0,0,1],[1,1,0],[0,1,0]])
y = np.array([[0],[0],[1],[1]])
np.random.seed(2)

In [ ]:
wt = np.random.random((3,1))
wt

array([[0.4359949 ],
       [0.02592623],
       [0.54966248]])

In [ ]:
sum = np.dot(x, wt) + 0.02
sum

array([[1.00565738],
       [0.56966248],
       [0.48192113],
       [0.04592623]])

In [ ]:
def tf(a):
  return 1/(1+np.exp(-a))

In [ ]:
tf(3)

0.9525741268224334

In [ ]:
yp = tf(sum)
yp

array([[0.73216943],
       [0.63868529],
       [0.61820142],
       [0.51147954]])

In [ ]:
yp.round()

array([[1.],
       [1.],
       [1.],
       [1.]])

In [ ]:
e = y - yp

In [ ]:
e

array([[-0.73216943],
       [-0.63868529],
       [ 0.38179858],
       [ 0.48852046]])

In [ ]:
def gr(a,b):
  return a*(b*(1-b))
cw = gr(e,yp)
w = wt + np.dot(x.T, cw)
w

array([[0.38253373],
       [0.23810729],
       [0.25869889]])

In [ ]:
for i in range(500):
  sum = np.dot(x, wt) + 0.02
  yp = tf(sum)
  e = y-yp
  cw = gr(e,yp)
  wt = wt+np.dot(x.T, cw)

In [ ]:
print("Error",e)
print("ypred",yp)

Error [[-0.02344894]
 [-0.02342859]
 [ 0.02343527]
 [ 0.02345562]]
ypred [[0.02344894]
 [0.02342859]
 [0.97656473]
 [0.97654438]]


In [ ]:
yp.round()
x.T.shape

(3, 4)

In [ ]:
new_x = np.array([0,1,1])
sum_new = np.dot(new_x, wt)+0.02
ypred_new = tf(sum_new)
ypred_new

array([0.49470516])